version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run tests
          command: npm test
  build-push:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Docker Build and Push
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            docker build -t eu.gcr.io/frontend-challenge-319616/client -t eu.gcr.io/frontend-challenge-319616/client:$TAG .
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "eu.gcr.io"
          image: "client"
      - cloudrun/deploy:
          platform: "managed"
          image: "eu.gcr.io/$GOOGLE_PROJECT_ID/client"
          service-name: "orb-gcp-cloud-run"
          region: $GOOGLE_COMPUTE_ZONE
          unauthenticated: true

workflows:
  ci:
    jobs:
      - build-and-test
      - build-push:
          requires:
            - build-and-test
